// Fenix/Fennec only!
// Why? Answer: IceCat is less maintained and comes with LibreJS and related addons preinstalled.
// Tor integration is planned for Q3: https://wiki.mozilla.org/Release_Management/Calendar#Future_branch_dates.
//
// v0.9.1
//
// Rename the user-android.js file to user.js!
// Put the file under: /data/data/org.mozilla.fennec_fdroid/files/mozilla/xxxxxx.default/ (make sure xxxxxx is your profile ID and correct profile folder!)
//
// Importing .p12 user certificates on Fennec
// https://www.reddit.com/r/firefox/comments/c02jpn/howto_importing_p12_user_certificates_on_fennec/

//user_pref("xpinstall.signatures.required", false); // only enable it up to 66.0.4 -> bug 1548973
//user_pref("browser.altClickSave", true); // only enable i to save addons to disk (give Firefox storage permissions! which is a workaround in case AMO doesn not allow you to install the addons!
user_pref("browser.aboutConfig.showWarning", false);
user_pref("general.aboutConfig.enable", true);
// user_pref("accessibility.typeaheadfind", false);
// user_pref("browser.download.folderList", 2);
// user_pref("browser.urlbar.clickSelectsAll", false);
// user_pref("clipboard.autocopy", false);
// user_pref("dom.disable_beforeunload", true);
user_pref("dom.indexedDB.enabled", false);
// user_pref("dom.storage.enabled", false);
user_pref("gfx.color_management.mode", 1);
user_pref("gfx.color_management.enablev4", true);
// user_pref("font.name-list.emoji", "Noto Color Emoji");
// user_pref("font.name.monospace.ar", "Noto Naskh Arabic");
// user_pref("font.name.monospace.el", "Noto Sans Mono");
// user_pref("font.name.monospace.he", "Noto Sans Hebrew");
// user_pref("font.name.monospace.ja", "Noto Sans CJK JP");
// user_pref("font.name.monospace.ko", "Noto Sans CJK KR");
// user_pref("font.name.monospace.th", "Noto Sans Thai");
// user_pref("font.name.monospace.x-armn", "Noto Sans Armenian");
// user_pref("font.name.monospace.x-beng", "Noto Sans Bengali");
// user_pref("font.name.monospace.x-cans", "monospace");
// user_pref("font.name.monospace.x-cyrillic", "Noto Mono");
// user_pref("font.name.monospace.x-devanagari", "Noto Sans Devanagari");
// user_pref("font.name.monospace.x-ethi", "Noto Sans Ethiopic");
// user_pref("font.name.monospace.x-geor", "Noto Sans Georgian");
// user_pref("font.name.monospace.x-gujr", "Noto Sans Gujarati");
// user_pref("font.name.monospace.x-guru", "Noto Sans Gurmukhi");
// user_pref("font.name.monospace.x-khmr", "Noto Sans Khmer");
// user_pref("font.name.monospace.x-knda", "Noto Sans Kannada");
// user_pref("font.name.monospace.x-math", "Latin Modern Math");
// user_pref("font.name.monospace.x-mlym", "Noto Sans Malayalam");
// user_pref("font.name.monospace.x-orya", "Noto Sans Oriya");
// user_pref("font.name.monospace.x-sinh", "Noto Sans Sinhala");
// user_pref("font.name.monospace.x-tamil", "Noto Sans Tamil");
// user_pref("font.name.monospace.x-telu", "Noto Sans Telugu");
// user_pref("font.name.monospace.x-tibt", "Noto Sans Tibetan");
// user_pref("font.name.monospace.x-unicode", "Noto Mono");
// user_pref("font.name.monospace.x-western", "Noto Mono");
// user_pref("font.name.monospace.zh-CN", "Noto Sans CJK SC");
// user_pref("font.name.monospace.zh-HK", "Noto Sans CJK TC");
// user_pref("font.name.monospace.zh-TW", "Noto Sans CJK TC");
// user_pref("font.name.sans-serif.ar", "Noto Naskh Arabic");
// user_pref("font.name.sans-serif.el", "Noto Sans");
// user_pref("font.name.sans-serif.he", "Noto Sans Hebrew");
// user_pref("font.name.sans-serif.ja", "Noto Sans CJK JP");
// user_pref("font.name.sans-serif.ko", "Noto Sans CJK KR");
// user_pref("font.name.sans-serif.th", "Noto Sans Thai");
// user_pref("font.name.sans-serif.x-armn", "Noto Sans Armenian");
// user_pref("font.name.sans-serif.x-beng", "Noto Sans Bengali");
// user_pref("font.name.sans-serif.x-cans", "sans-serif");
// user_pref("font.name.sans-serif.x-cyrillic", "Noto Sans");
// user_pref("font.name.sans-serif.x-devanagari", "Noto Sans Devanagari");
// user_pref("font.name.sans-serif.x-ethi", "Noto Sans Ethiopic");
// user_pref("font.name.sans-serif.x-geor", "Noto Sans Georgian");
// user_pref("font.name.sans-serif.x-gujr", "Noto Sans Gujarati");
// user_pref("font.name.sans-serif.x-guru", "Noto Sans Gurmukhi");
// user_pref("font.name.sans-serif.x-khmr", "Noto Sans Khmer");
// user_pref("font.name.sans-serif.x-knda", "Noto Sans Kannada");
// user_pref("font.name.sans-serif.x-math", "Latin Modern Math");
// user_pref("font.name.sans-serif.x-mlym", "Noto Sans Malayalam");
// user_pref("font.name.sans-serif.x-orya", "Noto Sans Oriya");
// user_pref("font.name.sans-serif.x-sinh", "Noto Sans Sinhala");
// user_pref("font.name.sans-serif.x-tamil", "Noto Sans Tamil");
// user_pref("font.name.sans-serif.x-telu", "Noto Sans Telugu");
// user_pref("font.name.sans-serif.x-tibt", "Noto Sans Tibetan");
// user_pref("font.name.sans-serif.x-unicode", "Noto Sans");
// user_pref("font.name.sans-serif.x-western", "Noto Sans");
// user_pref("font.name.sans-serif.zh-CN", "Noto Sans CJK SC");
// user_pref("font.name.sans-serif.zh-HK", "Noto Sans CJK TC");
// user_pref("font.name.sans-serif.zh-TW", "Noto Sans CJK TC");
// user_pref("font.name.serif.ar", "Noto Naskh Arabic");
// user_pref("font.name.serif.el", "Noto Serif");
// user_pref("font.name.serif.he", "Noto Serif Hebrew");
// user_pref("font.name.serif.ja", "Noto Serif CJK JP");
// user_pref("font.name.serif.ko", "Noto Serif CJK KR");
// user_pref("font.name.serif.th", "Noto Serif Thai");
// user_pref("font.name.serif.x-armn", "Noto Serif Armenian");
// user_pref("font.name.serif.x-beng", "Noto Serif Bengali");
// user_pref("font.name.serif.x-cans", "serif");
// user_pref("font.name.serif.x-cyrillic", "Noto Serif");
// user_pref("font.name.serif.x-devanagari", "Noto Serif Devanagari");
// user_pref("font.name.serif.x-ethi", "Noto Serif Ethiopic");
// user_pref("font.name.serif.x-geor", "Noto Serif Georgian");
// user_pref("font.name.serif.x-gujr", "Noto Serif Gujarati");
// user_pref("font.name.serif.x-guru", "Noto Serif Gurmukhi");
// user_pref("font.name.serif.x-khmr", "Noto Serif Khmer");
// user_pref("font.name.serif.x-knda", "Noto Serif Kannada");
// user_pref("font.name.serif.x-math", "Latin Modern Math");
// user_pref("font.name.serif.x-mlym", "Noto Serif Malayalam");
// user_pref("font.name.serif.x-orya", "Noto Sans Oriya");
// user_pref("font.name.serif.x-sinh", "Noto Serif Sinhala");
// user_pref("font.name.serif.x-tamil", "Noto Serif Tamil");
// user_pref("font.name.serif.x-telu", "Noto Serif Telugu");
// user_pref("font.name.serif.x-tibt", "Noto Sans Tibetan");
// user_pref("font.name.serif.x-unicode", "Noto Serif");
// user_pref("font.name.serif.x-western", "Noto Serif");
// user_pref("font.name.serif.zh-CN", "Noto Serif CJK SC");
// user_pref("font.name.serif.zh-HK", "Noto Serif CJK TC");
// user_pref("font.name.serif.zh-TW", "Noto Serif CJK TC");
// user_pref("full-screen-api.enabled", false);
// user_pref("general.appname.override", "");
// user_pref("general.appversion.override", "");
// user_pref("general.oscpu.override", "");
// user_pref("general.platform.override", "");
// user_pref("general.useragent.locale", "");
// user_pref("general.useragent.override", "");
// user_pref("general.useragent.site_specific_overrides", false);
// user_pref("general.useragent.updates.lastupdated", "");
// user_pref("identity.fxaccounts.auth.uri", "");
// user_pref("intl.locale.requested", "en-US");
// user_pref("javascript.enabled", false);
// user_pref("keyword.enabled", false);
// user_pref("layers.acceleration.disabled", true);
// user_pref("layers.acceleration.force-enabled", false);
// user_pref("mathml.disabled", true);
// user_pref("media.default_volume", "0.5");
// user_pref("media.media-capabilities.enabled", false);
// user_pref("middlemouse.contentLoadURL", false);
// user_pref("narrate.enabled", false);
// user_pref("network.http.spdy.enabled.deps", false);
// user_pref("network.http.spdy.enabled.http2", false);
// user_pref("network.http.spdy.enabled", false);
// user_pref("network.http.spdy.websockets", false);
// user_pref("network.trr.bootstrapAddress", "");
// user_pref("network.trr.custom_uri", "");
// user_pref("network.trr.mode", 0);
// user_pref("network.trr.uri", "");
// user_pref("nglayout.enable_drag_images", false);
// user_pref("reader.parse-on-load.enabled", false);
// user_pref("security.OCSP.require", true);
// user_pref("security.tls.version.max", 4);
// user_pref("security.tls.version.min", 3);
// user_pref("toolkit.cosmeticAnimations.enabled", false);
// user_pref("view_source.wrap_long_lines", true);
user_pref("layout.frame_rate", 90);
user_pref("browser.newtabpage.activity-stream.topSitesRows", 4);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.feeds.aboutpreferences", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.sectionOrder", "topsites");
user_pref("browser.library.activity-stream.enabled", false);
user_pref("extensions.pocket.enabled", false);
user_pref("accessibility.force_disabled", 0);
user_pref("services.sync.enabled", false);
user_pref("alerts.showFavicons", false);
//user_pref("extensions.screenshots.upload-disabled", true);
user_pref("extensions.screenshots.disabled", true);
user_pref("app.feedback.baseURL", "");
user_pref("app.update.channel", "");
user_pref("app.support.baseURL", "");
user_pref("app.update.autodownload", "never");
user_pref("app.feedbackURL", "");
user_pref("app.channelURL", "");
user_pref("app.faqURL", "");
user_pref("devtools.devices.url", "");
user_pref("browser.chrome.errorReporter.infoURL", "");
user_pref("app.supportURL", "");
user_pref("general.useragent.updates.url", "");
user_pref("network.trr.confirmationNS", "");
user_pref("media.decoder-doctor.new-issue-endpoint", "");
user_pref("app.privacyURL", "");
user_pref("general.useragent.updates.enabled", false);
user_pref("app.releaseNotesURL", "https://www.mozilla.org/en-US/firefox/%VERSION%/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=whatsnew");
user_pref("app.creditsURL", "");
user_pref("apz.allow_double_tap_zooming", true);
user_pref("apz.allow_immediate_handoff", false);
user_pref("apz.allow_zooming", true);
user_pref("apz.android.chrome_fling_physics.enabled", true);
user_pref("apz.android.chrome_fling_physics.friction", "0.015");
user_pref("apz.android.chrome_fling_physics.inflexion", "0.35");
user_pref("apz.android.chrome_fling_physics.stop_threshold", "0.1");
user_pref("apz.autoscroll.enabled", true);
user_pref("apz.axis_lock.breakout_angle", "0.3926991");
user_pref("apz.axis_lock.breakout_threshold", "0.03125");
user_pref("apz.axis_lock.direct_pan_angle", "1.047197");
user_pref("apz.axis_lock.lock_angle", "0.5235987");
user_pref("apz.axis_lock.mode", 0);
user_pref("apz.content_response_timeout", 400);
user_pref("apz.danger_zone_x", 50);
user_pref("apz.danger_zone_y", 100);
user_pref("apz.disable_for_scroll_linked_effects", false);
user_pref("apz.displayport_expiry_ms", 15000);
user_pref("apz.drag.enabled", true);
user_pref("apz.drag.initial.enabled", true);
user_pref("apz.drag.touch.enabled", true);
user_pref("apz.enlarge_displayport_when_clipped", false);
user_pref("apz.fixed-margin-override.bottom", 0);
user_pref("apz.fixed-margin-override.enabled", false);
user_pref("apz.fixed-margin-override.top", 0);
user_pref("apz.fling_accel_base_mult", "1.0");
user_pref("apz.fling_accel_interval_ms", 299);
user_pref("apz.fling_accel_min_velocity", "1.5");
user_pref("apz.fling_accel_supplemental_mult", "1.0");
user_pref("apz.fling_curve_threshold_inches_per_ms", "-1.0");
user_pref("apz.fling_friction", "0.002");
user_pref("apz.fling_min_velocity_threshold", "0.5");
user_pref("apz.fling_stop_on_tap_threshold", "0.05");
user_pref("apz.fling_stopped_threshold", "0.01");
user_pref("apz.frame_delay.enabled", true);
user_pref("apz.keyboard.passive-listeners", false);
user_pref("apz.keyboard.passive-listeners", true);
user_pref("apz.max_tap_time", 300);
user_pref("apz.max_velocity_inches_per_ms", "-1.0");
user_pref("apz.min_skate_speed", "1.0");
user_pref("apz.minimap.enabled", false);
user_pref("apz.one_touch_pinch.enabled", true);
user_pref("apz.overscroll.enabled", false);
user_pref("apz.overscroll.min_pan_distance_ratio", "1.0");
user_pref("apz.overscroll.spring_friction", "0.015");
user_pref("apz.overscroll.spring_stiffness", "0.0018");
user_pref("apz.overscroll.stop_distance_threshold", "5.0");
user_pref("apz.overscroll.stop_velocity_threshold", "0.01");
user_pref("apz.overscroll.stretch_factor", "0.35");
user_pref("apz.paint_skipping.enabled", true);
user_pref("apz.peek_messages.enabled", true);
user_pref("apz.pinch_lock.mode", 1);
user_pref("apz.pinch_lock.scoll_lock_threshold", "0.03125");
user_pref("apz.pinch_lock.span_breakout_threshold", "0.03125");
user_pref("apz.pinch_lock.span_lock_threshold", "0.03125");
user_pref("apz.popups.enabled", false);
user_pref("apz.printtree", false);
user_pref("apz.record_checkerboarding", false);
user_pref("apz.relative-update.enabled", true);
user_pref("apz.scale_repaint_delay_ms", 500);
user_pref("apz.second_tap_tolerance", "0.5");
user_pref("apz.test.logging_enabled", false);
user_pref("apz.touch_move_tolerance", "0.1");
user_pref("apz.touch_start_tolerance", "0.1");
user_pref("apz.velocity_bias", "0.0");
user_pref("apz.velocity_relevance_time_ms", 150);
user_pref("apz.x_skate_highmem_adjust", "0.0");
user_pref("apz.x_skate_size_multiplier", "1.25");
user_pref("apz.x_stationary_size_multiplier", "1.5");
user_pref("apz.y_skate_highmem_adjust", "0.0");
user_pref("apz.y_skate_size_multiplier", "3.5");
user_pref("apz.y_stationary_size_multiplier", "3.5");
user_pref("apz.zoom_animation_duration_ms", 250);
user_pref("beacon.enabled", false);
user_pref("breakpad.reportURL", "");
user_pref("browser.bookmarks.max_backups", 3);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.memory.capacity", 0);
user_pref("browser.cache.memory.enable", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.cache.offline.insecure.enable", false);
user_pref("browser.chrome.dynamictoolbar", false);
user_pref("browser.contentblocking.enabled", true);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.forbid_open_with", true);
user_pref("browser.download.forward_oma_android_download_manager", false);
user_pref("browser.download.manager.addToRecentDocs", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.drag_out_of_frame_style", 1);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.fixup.alternate.prefix", "");
user_pref("browser.fixup.alternate.suffix", "");
user_pref("browser.formfill.enable", false);
user_pref("browser.formfill.expire_days", 0);
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("extensions.formautofill.heuristics.enabled", false);
user_pref("browser.link.open_newwindow", 3);
user_pref("browser.safebrowsing.allowOverride", false);
user_pref("browser.safebrowsing.blockedURIs.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.provider.google.gethashURL", "");
user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.provider.google.reportURL", "");
user_pref("browser.safebrowsing.provider.google.updateURL", "");
user_pref("browser.safebrowsing.provider.google4.dataSharing.enabled", false);
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.safebrowsing.provider.google4.gethashURL", "");
user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.provider.google4.reportURL", "");
user_pref("browser.safebrowsing.provider.google4.updateURL", "");
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
user_pref("browser.safebrowsing.provider.mozilla.lists", "");
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
user_pref("browser.safebrowsing.reportPhishURL", "");
user_pref("browser.search.geoip.timeout", 0);
user_pref("browser.search.geoip.url", "");
user_pref("browser.search.geoSpecificDefaults.url", "");
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.region", "US");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update.log", false);
user_pref("browser.search.update", false);
user_pref("browser.search.noCurrentEngine", true);
user_pref("browser.send_pings.max_per_link", 0);
user_pref("browser.send_pings.require_same_host", true);
user_pref("browser.send_pings", false);
user_pref("browser.sessionhistory.max_entries", 10);
user_pref("browser.sessionhistory.max_total_viewers", 0);
user_pref("browser.sessionstore.interval", 70000);
user_pref("browser.sessionstore.max_tabs_undo", 10);
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.snippets.enabled", false);
user_pref("browser.snippets.firstrunHomepage.enabled", false);
user_pref("browser.snippets.geoUrl", "");
user_pref("browser.snippets.statsUrl", "");
user_pref("webextensions.storage.sync.serverURL", "");
user_pref("browser.snippets.syncPromo.enabled", false);
//user_pref("browser.snippets.updateInterval", 0);
user_pref("browser.snippets.updateUrl", "");
user_pref("browser.ssl_override_behavior", 2);
user_pref("browser.tabs.remote.allowLinkedWebInFileUriProcess", false);
user_pref("browser.tabs.remote.autostart", true);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("browser.xul.error_pages.expert_bad_cert", true);
user_pref("canvas.capturestream.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("device.sensors.enabled", false);
user_pref("device.storage.enabled", false)
user_pref("devtools.chrome.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("devtools.debugger.logging", false);
user_pref("datareporting.policy.currentPolicyVersion", 0);
user_pref("devtools.debugger.remote-enabled", false);
user_pref("devtools.debugger.remote-enabled", true);
//user_pref("browser.discovery.enabled", false);
user_pref("datareporting.policy.currentPolicyAcceptedVersion", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 0);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", false);
user_pref("datareporting.policy.minimumPolicyVersion", 0);
user_pref("datareporting.policy.minimumPolicyVersion.channel-beta", 0);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "");
user_pref("datareporting.policy.firstRunURL", "");
user_pref("devtools.enabled", false);
user_pref("devtools.onboarding.telemetry.logged", false);
user_pref("devtools.remote.usb.enabled", true);
user_pref("devtools.remote.wifi.scan", false);
user_pref("devtools.webide.enabled", false);
user_pref("dom.allow_cut_copy", false); // Hidden preference
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.battery.enabled", false);
user_pref("dom.caches.enabled", false);
user_pref("dom.disable_open_during_load", true);
user_pref("dom.disable_window_flip", true);
user_pref("dom.disable_window_move_resize", true);
user_pref("dom.disable_window_open_feature.close", true);
user_pref("dom.disable_window_open_feature.location", true);
user_pref("dom.disable_window_open_feature.menubar", true);
user_pref("dom.disable_window_open_feature.minimizable", true);
user_pref("dom.disable_window_open_feature.personalbar", true);
user_pref("dom.disable_window_open_feature.resizable", true);
user_pref("dom.disable_window_open_feature.status", true);
user_pref("dom.disable_window_open_feature.toolbar", true);
user_pref("devtools.webide.autoinstallADBHelper", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("dom.enable_performance_navigation_timing", false);
user_pref("dom.enable_performance_observer", false);
user_pref("dom.enable_performance", false);
user_pref("dom.enable_resource_timing", false);
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("dom.event.highrestimestamp.enabled", true);
user_pref("dom.fileHandle.enabled", false);
user_pref("dom.forms.datetime.others", false);
user_pref("dom.forms.datetime.timepicker", false);
user_pref("dom.forms.datetime", false);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.gamepad.extensions.enabled", false);
user_pref("dom.gamepad.haptic_feedback.enabled", false);
user_pref("dom.gamepad.test.enabled", false);
user_pref("dom.imagecapture.enabled", false);
user_pref("dom.indexedDB.experimental", false);
user_pref("dom.indexedDB.logging.details", false);
user_pref("dom.indexedDB.logging.enabled", false);
user_pref("dom.indexedDB.logging.profiler-marks", false);
user_pref("toolkit.telemetry.geckoview.streaming", false);
user_pref("toolkit.telemetry.isGeckoViewMode", false);
user_pref("toolkit.telemetry.testing.overrideProductsCheck", false);
user_pref("dom.IntersectionObserver.enabled", false);
user_pref("dom.ipc.plugins.flash.subprocess.crashreporter.enabled", false);
user_pref("dom.ipc.plugins.reportCrashURL", false);
user_pref("dom.netinfo.enabled", false);
user_pref("dom.performance.enable_scheduler_timing", false);
user_pref("dom.performance.enable_user_timing_logging", false);
user_pref("dom.popup_allowed_events", "click dblclick");
user_pref("dom.popup_maximum", 3);
user_pref("dom.push.connection.enabled", false);
user_pref("dom.push.enabled", true);
user_pref("dom.push.serverURL", "wss://push.services.mozilla.com/");
user_pref("dom.push.userAgentID", "");
user_pref("dom.serviceWorkers.enabled", false);
user_pref("dom.storageManager.enabled", false);
user_pref("dom.targetBlankNoOpener.enabled", true);
user_pref("dom.vibrator.enabled", false);
user_pref("dom.vr.enabled", false);
user_pref("dom.vr.service.enabled", false);
user_pref("dom.w3c_pointer_events.enabled", false);
user_pref("layout.accessiblecaret.hapticfeedback", false);
//user_pref("extensions.legacy.enabled", false);
user_pref("dom.w3c_touch_events.enabled", 0);
user_pref("dom.registerProtocolHandler.insecure.enabled", false);
user_pref("dom.webaudio.enabled", false);
user_pref("extensions.update.background.url", "https://versioncheck-bg.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=en-US&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%");
user_pref("dom.webnotifications.enabled", false);
user_pref("extensions.update.url", "https://versioncheck-bg.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=en-US&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%");
user_pref("dom.webnotifications.serviceworker.enabled", false);
user_pref("extensions.autoDisableScopes", 15);
user_pref("extensions.autoupdate.enabled", true);
user_pref("media.webvtt.testing.events", false);
user_pref("media.webvtt.debug.logging", false);
//user_pref("extensions.installDistroAddons", false);
user_pref("extensions.blocklist.url", "https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%20/%20/");
user_pref("extensions.enabledScopes", 1);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.getAddons.search.browseURL", "https://addons.mozilla.org/%LOCALE%/android/search?q=%TERMS%");
user_pref("extensions.logging.enabled", false);
user_pref("extensions.update.enabled", true);
user_pref("extensions.webcompat-reporter.enabled", false);
user_pref("extensions.webcompat-reporter.newIssueEndpoint", "");
user_pref("extensions.webextensions.enablePerformanceCounters", false);
user_pref("extensions.webextensions.restrictedDomains", "");
user_pref("font.default.el", "sans-serif");
user_pref("font.size.monospace.ar", 12);
user_pref("full-screen-api.warning.delay", 0);
user_pref("full-screen-api.warning.timeout", 0);
user_pref("general.warnOnAboutConfig", false);
user_pref("geo.enabled", false);
user_pref("gfx.bundled_fonts.enabled", true);
user_pref("gfx.bundled_fonts.force-enabled", false);
user_pref("gfx.downloadable_fonts.keep_color_bitmaps", false);
user_pref("gfx.font_rendering.graphite.enabled", false);
user_pref("gfx.logging.painted-pixel-count.enabled", false);
user_pref("gfx.logging.peak-texture-usage.enabled", false);
user_pref("gfx.logging.texture-usage.enabled", false);
user_pref("gfx.offscreencanvas.enabled", false);
user_pref("home.sync.updateMode", 0);
user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.charset.detector", "");
user_pref("intl.ime.hack.on_any_apps.fire_key_events_for_composition", false);
user_pref("intl.ime.hack.on_ime_unaware_apps.fire_key_events_for_composition", false);
user_pref("intl.ime.hack.set_input_scope_of_url_bar_to_default", true);
user_pref("intl.ime.hack.uim.using_key_snooper", true);
user_pref("intl.locale.requested", "en-US");
user_pref("network.cookie.lifetime.days", 1);
user_pref("intl.regional_prefs.use_os_locales", false);
user_pref("extensions.blocklist.useXML", false);
user_pref("javascript.options.asmjs", false);
user_pref("javascript.options.asyncstack", false);
user_pref("javascript.options.wasm", false);
user_pref("layout.css.clip-path-shapes.enabled", false);
user_pref("layout.css.visited_links_enabled", false);
user_pref("layout.display-list.retain.chrome", true);
user_pref("layout.display-list.retain", true);
user_pref("layout.spellcheckDefault", 2);
user_pref("media.autoplay.allow-muted", false);
user_pref("media.autoplay.ask-permission", true);
user_pref("media.autoplay.enabled.user-gestures-needed", false);
user_pref("media.autoplay.allow-extension-background-pages", false);
user_pref("media.autoplay.block-event.enabled", true);
user_pref("media.autoplay.block-webaudio", true);
user_pref("media.autoplay.default", 5);
user_pref("media.av1.enabled", true);
user_pref("media.av1.use-dav1d", false);
user_pref("media.block-autoplay-until-in-foreground", true);
user_pref("media.cubeb.sandbox", false);
user_pref("media.eme.enabled", false);
user_pref("media.getusermedia.agc_enabled", false);
user_pref("media.getusermedia.audiocapture.enabled", false);
user_pref("media.getusermedia.browser.enabled", false);
user_pref("media.getusermedia.camera.off_while_disabled.enabled", false);
user_pref("media.getusermedia.microphone.off_while_disabled.enabled", false);
user_pref("network.netlink.route.check.IPv4", "");
user_pref("network.netlink.route.check.IPv6", "");
user_pref("media.getusermedia.noise_enabled", false);
user_pref("media.getusermedia.screensharing.enabled", false);
user_pref("media.gmp-gmpopenh264.autoupdate", false);
user_pref("media.gmp-gmpopenh264.enabled", false);
user_pref("media.gmp-manager.buildID", "20200402050101");
user_pref("media.gmp-manager.cert.checkAttributes", false);
user_pref("media.gmp-manager.cert.requireBuiltIn", false);
user_pref("plugin.defaultXpi.state", 0);
user_pref("media.gmp-manager.certs.1.commonName", "");
user_pref("media.gmp-manager.certs.1.issuerName", "");
user_pref("media.gmp-manager.certs.2.commonName", "");
user_pref("media.gmp-manager.certs.2.issuerName", "");
user_pref("media.gmp-manager.lastCheck", "");
user_pref("media.gmp-manager.updateEnabled", false);
user_pref("toolkit.telemetry.hybridContent.enabled", false);
user_pref("media.gmp-manager.url.override", "data:text/plain,");
user_pref("media.gmp-manager.url", "data:text/plain,");
user_pref("media.gmp-provider.enabled", false);
user_pref("webgl.cgl.multithreaded", false);
user_pref("webgl.dxgl.enabled", false);
user_pref("media.gmp.trial-create.enabled", false);
user_pref("media.mediasource.webm.audio.enabled", true);
user_pref("media.mediasource.webm.enabled", true);
user_pref("media.navigator.enabled", false);
user_pref("media.navigator.mediadatadecoder_h264_enabled", true); // false, in problems
user_pref("media.navigator.mediadatadecoder_vpx_enabled", false);
user_pref("media.navigator.video.enabled", false);
user_pref("media.ondevicechange.enabled", false);
user_pref("media.peerconnection.dtmf.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("media.peerconnection.ice.no_host", true);
user_pref("media.peerconnection.ice.tcp", false);
user_pref("media.peerconnection.identity.enabled", false);
user_pref("media.peerconnection.identity.timeout", 1);
user_pref("media.peerconnection.rtpsourcesapi.enabled", false);
user_pref("media.peerconnection.simulcast", false);
user_pref("media.peerconnection.turn.disable", true);
user_pref("media.peerconnection.use_document_iceservers", false);
user_pref("media.peerconnection.video.enabled", false);
user_pref("media.plugins.enabled", false);
user_pref("media.video_stats.enabled", false);
user_pref("media.webspeech.recognition.enable", false);
user_pref("network.captive-portal-service.backoffFactor", "");
user_pref("media.webspeech.synth.enabled", false);
user_pref("network.allow-experiments", false);
user_pref("network.auth.subresource-http-auth-allow", 1);
user_pref("network.auth.subresource-img-cross-origin-http-auth-allow", false);
user_pref("network.captive-portal-service.enabled", false);
//work with success.txt for CPS ^^
//user_pref("captivedetect.canonicalURL", http://www.,,,,,success.txt);
user_pref("network.captive-portal-service.minInterval", 35);
user_pref("network.connectivity-service.DNSv4.domain", "");
user_pref("network.connectivity-service.DNSv6.domain", "");
user_pref("network.connectivity-service.enabled", false);
user_pref("lightweightThemes.persistedThemeID", "");
user_pref("extensions.htmlaboutaddons.enabled", false);
user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("network.connectivity-service.IPv4.url", "");
user_pref("browser.contentblocking.database.enabled", false);
user_pref("extensions.abuseReport.enabled", false);
user_pref("extensions.abuseReport.openDialog", false);
user_pref("extensions.abuseReport.amWebAPI.enabled", false);
user_pref("extensions.abuseReport.url", "");
user_pref("extensions.abuseReport.amoDetailsURL", "");
user_pref("network.connectivity-service.IPv6.url", "");
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.leave-secure-alone", true);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("extensions.recommendations.themeRecommendationUrl", "");
user_pref("extensions.recommendations.privacyPolicyUrl", "");
user_pref("network.cookie.same-site.enabled", true);
user_pref("network.cookie.thirdparty.nonsecureSessionOnly", true);
user_pref("network.cookie.thirdparty.sessionOnly", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dns.disablePrefetchFromHTTPS", true);
user_pref("network.http.active_tab_priority", false);
user_pref("network.http.altsvc.enabled", false);
user_pref("network.http.altsvc.oe", false);
user_pref("network.http.max-connections", 40);
user_pref("network.http.redirection-limit", 10);
user_pref("network.http.referer.defaultPolicy.pbmode", 2);
user_pref("network.http.referer.defaultPolicy", 3);
user_pref("network.http.referer.hideOnionSource", false);
user_pref("network.http.referer.spoofSource", true);
user_pref("network.http.referer.trimmingPolicy", 0);
user_pref("network.http.referer.XOriginPolicy", 1);
user_pref("network.http.referer.XOriginTrimmingPolicy", 0);
user_pref("network.http.sendRefererHeader", 2);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.IDN_show_punycode", true);
user_pref("network.notify.changed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enable-hover-on-ssl", false);
user_pref("network.predictor.enable-prefetch", false);
user_pref("network.predictor.enabled", false);
user_pref("network.predictor.preconnect-min-confidence", 101);
user_pref("network.predictor.prefetch-min-confidence", 101);
user_pref("network.predictor.prefetch-rolling-load-count", 0);
user_pref("network.predictor.preresolve-min-confidence", 101);
user_pref("network.prefetch-next", false);
user_pref("network.preload", false);
user_pref("network.protocol-handler.warn-external.file", false);
user_pref("network.proxy.autoconfig_url.include_path", false);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.security.ports.banned", "9050,9051,9150,9151");
user_pref("network.tickle-wifi.enabled", false);
user_pref("network.warnOnAboutNetworking", false);
user_pref("offline-apps.allow_by_default", false);
user_pref("plugin.default.state", 0);
user_pref("plugin.disable", false);
user_pref("plugin.sessionPermissionNow.intervalInMinutes", 0);
user_pref("plugins.click_to_play", true);
user_pref("print.print_via_parent", true);
user_pref("privacy.donottrackheader.enabled", false);
user_pref("privacy.firstparty.isolate.restrict_opener_access", true);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.trackingprotection.enabled",	false);
user_pref("privacy.trackingprotection.enabled", false);
user_pref("privacy.trackingprotection.introURL", "");
user_pref("privacy.trackingprotection.pbmode.enabled", false);
user_pref("private.data.cookies_sessions
user_pref("security.ask_for_password", 2);
user_pref("security.cert_pinning.enforcement_level", 2);
user_pref("security.csp.enable_violation_events", false);
user_pref("security.csp.enable", true);
user_pref("security.csp.experimentalEnabled", false);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.slowStartup.maxSamples", 0);
user_pref("security.data_uri.block_toplevel_data_uri_navigations", true);
user_pref("browser.slowStartup.notificationDisabled", true);
user_pref("security.dialog_enable_delay", 0);
user_pref("security.family_safety.mode", 0);
user_pref("security.insecure_field_warning.contextual.enabled", true);
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.mixed_content.block_display_content", true);
user_pref("security.mixed_content.block_object_subrequest", true);
user_pref("security.OCSP.enabled", 1);
user_pref("security.OCSP.require", true);
user_pref("security.password_lifetime", 5);
user_pref("security.pki.distrust_ca_policy", 2);
user_pref("security.pki.sha1_enforcement_level", 1);
user_pref("security.sandbox.logging.enabled", false);
user_pref("security.ssl.disable_session_identifiers", true);
user_pref("security.ssl.enable_ocsp_must_staple", true);
user_pref("security.ssl.enable_ocsp_stapling", true);
user_pref("security.ssl.errorReporting.automatic", false);
user_pref("security.ssl.errorReporting.enabled", false);
user_pref("security.ssl.errorReporting.url", "");
user_pref("security.ssl.require_safe_negotiation", true);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.rsa_des_ede3_sha", false);
user_pref("security.strict_security_checks.enabled", false);
user_pref("security.tls.enable_0rtt_data", false);
user_pref("security.tls.version.fallback-limit", 3);
user_pref("signon.rememberSignons", false);
user_pref("signon.rememberSignons.visibilityToggle", true);
user_pref("signon.autofillForms", true);
user_pref("signon.autofillForms.autocompleteOff", true);
user_pref("signon.autofillForms.http", false);
user_pref("signon.autologin.proxy", false);
user_pref("signon.formlessCapture.enabled", true);
user_pref("signon.generation.available", false);
user_pref("signon.generation.enabled", false);
user_pref("signon.privateBrowsingCapture.enabled", false);
user_pref("signon.storeWhenAutocompleteOff", true);
user_pref("signon.debug", false);
user_pref("signon.recipes.path", "");
user_pref("signon.schemeUpgrades", false);
user_pref("media.volume_scale", "1.0");
user_pref("signon.includeOtherSubdomainsInLookup", false);
user_pref("signon.masterPasswordReprompt.timeout_ms", 900000); // 15 Minutes
user_pref("signon.showAutoCompleteFooter", false);
user_pref("signon.showAutoCompleteOrigins", false);
user_pref("toolkit.telemetry.debugSlowSql", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "data:,");
user_pref("startup.homepage_welcome_url", "");
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("extensions.lastAppBuildId", "");
user_pref("toolkit.coverage.opt-out", true);
user_pref("startup.homepage_override_url", "");
user_pref("browser.pagethumbnails.capturing_disabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("ui.android.mouse_as_touch", 1);
user_pref("toolkit.coverage.endpoint.base", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("ui.use_standins_for_native_colors", true);
user_pref("urlclassifier.trackingAnnotationSkipURLs", "google.com/recaptcha/,*.google.com/recaptcha/");
user_pref("urlclassifier.blockedTable", "");
user_pref("urlclassifier.disallow_completions", "");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("urlclassifier.downloadAllowTable", "");
user_pref("urlclassifier.downloadBlockTable", "");
user_pref("urlclassifier.flashAllowExceptTable", "");
user_pref("urlclassifier.flashAllowTable", "");
user_pref("urlclassifier.flashExceptTable", "");
user_pref("urlclassifier.flashSubDocExceptTable", "");
user_pref("urlclassifier.flashSubDocTable", "");
user_pref("urlclassifier.flashTable", "");
user_pref("urlclassifier.malwareTable", "");
user_pref("urlclassifier.passwordAllowTable", "");
user_pref("urlclassifier.phishTable", "");
user_pref("urlclassifier.trackingTable", "");
user_pref("urlclassifier.trackingWhitelistTable", "");
user_pref("webchannel.allowObject.urlWhitelist", "");
user_pref("webgl.disable-extensions", true);
user_pref("webgl.disable-fail-if-major-performance-caveat", true);
user_pref("webgl.disabled", true);
user_pref("webgl.enable-debug-renderer-info", false);
user_pref("webgl.enable-webgl2", false);
user_pref("webgl.force-enabled", false);
user_pref("webgl.min_capability_mode", true);
user_pref("webgl.msaa-force", false);
user_pref("xpinstall.whitelist.required", true);
user_pref("browser.urlbar.suggest.openpage", false);
// MIPS 32 - Spectre security vulnerability mitigations
//user_pref("javascript.options.spectre.index_masking", false);
//user_pref("javascript.options.spectre.object_mitigations.barriers", false);
//user_pref("javascript.options.spectre.object_mitigations.misc", false);
//user_pref("javascript.options.spectre.string_mitigations", false);
//user_pref("javascript.options.spectre.value_masking", false);
//user_pref("javascript.options.spectre.jit_to_C++_calls", false);
// MIPS 64
//user_pref("javascript.options.spectre.index_masking", true);
//user_pref("javascript.options.spectre.object_mitigations.barriers", true);
//user_pref("javascript.options.spectre.object_mitigations.misc", true);
//user_pref("javascript.options.spectre.string_mitigations", true);
//user_pref("javascript.options.spectre.value_masking", true);
//user_pref("javascript.options.spectre.jit_to_C++_calls", true);
